SELECT TOP 10 *
FROM [dbo].[KaggleV2-May-2016];

SELECT COUNT(*) as total_rows
FROM [dbo].[KaggleV2-May-2016];

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='KaggleV2-May-2016';

